export const CLOTHING_INIT = 'CLOTHING_INIT';
export const SET_SELECTED_ID = 'SET_SELECTED_ID';

export const CHECKOUT_INIT = 'CHECKOUT_INIT';
export const ADD_PRODUCT_TO_CHECKOUT = 'ADD_PRODUCT_TO_CHECKOUT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_CURRENT_PATH = 'SET_CURRENT_PATH';

export const SET_SEARCHING = 'SET_SEARCHING';

export const SHOWCASE_INIT = 'SHOWCASE_INIT';
export const SET_SHOWCASE_SELECTED_ID = 'SET_SHOWCASE_SELECTED_ID';

export const PRODUCT_INIT = 'PRODUCT_INIT';
export const SET_PRODUCT_SELECTED_ID = 'SET_PRODUCT_SELECTED_ID';
